### PR TITLE
add mayk to the menu, 2nd attempt

### PR DESCRIPTION
**Pull request by zeriaxdev**
Hey there. This probably might seem a bit strange, but I've decided to give it another shot. Right now it is working properly locally (screenshot), but I'm not really sure what to do about the date, since there is no date provided on the website and it's just the weekday.
the screenshot

### CODE REVIEW

**Comment by developerfromjokela** [comment]
One theoretical way would be to generate them . Do food menu items have some order? IE. First item is for Monday, second one for Tuesday, etc...

If so, you could generate dates for all weekdays.

Except if food menu is not up to date it will show old items as new. One way would be to cache response and compare if any new items are present. If they are, show as new items.

**Comment by developerfromjokela** [comment]
image

Also seems like they do contain week dates.

I remember you mentioned last time that they may randomly go missing. If that happens we could use that backup plan I mentioned prior.

**Comment by developerfromjokela** [comment]
If it has Vko text, you could get correct week thus generating correct weekday dates

**Comment by zeriaxdev** [comment]
When I meant that they go missing, the list does not the entire week - for example, only Thursday and Friday, like the last week, or on holidays, there is just none. Although I'm not sure if it can be something like "ma, ti, pe".

But alright, thanks for the solution, I'll work on this.

**Comment by zeriaxdev** [comment]
Alright, it seems to be fixed?
screenshot

**Comment by zeriaxdev** [comment]
Actually, this is a pretty bad solution, I'll try to improve it 😅

**Comment by zeriaxdev** [comment]
I think this should be better now.

**Comment by zeriaxdev** [comment]
Are you still reviewing this? I'm just clarifying, might as well improve it if needed?

**Comment by developerfromjokela** [comment]
Oh I'm sorry that it took this long, I was just busy. I'll make sure to check this within 2-3 days.

**Comment by developerfromjokela** [comment]
At this state it seems good if it works. I'll have to test your changes locally.

**Review by developerfromjokela — APPROVED** [review]

**Comment by developerfromjokela** [comment]
Thank you for your contribution!
This menu will be added to Wilma Plus app within a few days.

**Comment by zeriaxdev** [comment]
Thanks a lot!

**Pull request merged**
